### ISSUE TITLE
Apply clippy suggestions

### ISSUE THREAD

**Issue by simon-whitehead** [simon-whitehead/hakka#15]
`clippy` has some suggestions on what to do with various pieces of the code base. Within reason, it would be good to review these and apply them where necessary.

To get `clippy` working, install `rustup` then run:

    rustup run nightly cargo install clippy

..to install `clippy` via the nightly toolchain. Then run:

    rustup run nightly cargo clippy

To run clippy over the code base.

**Comment by seventh-chord** [comment]
Am looking into this right now (See 4a15b21250128b1532ce1cce025a9d5f182f9467). There are two clippy issues I would like to consult with you about before taking them on.

- The code does not compile on nightly, leading to a crash when running `rustup run nightly cargo clippy`. I don't know if clippy outputs any errors beyond the point where it crashes, so there might be some lints that we miss out on because of this.
- `execute_command` supposedly is to complex. I have an idea for fixing this and will open a new issue.

**Comment by simon-whitehead** [comment]
> The code doe snot compile on nightly

Ah, this is because of a silly error I made. I added `vm` as a dependency in the root `Cargo.toml`. Removing line 17 in `./Cargo.toml` lets it work.

**Comment by seventh-chord** [comment]
Ah, that fixes it. I guess the issue was that `vm` was declared both under `[dependencies]` and `[lib]`? Clippy does not output any more suggestions now, so I will open a pull request to close this issue.

**Comment by simon-whitehead** [comment]
Yeah when you declare the lib + binary in the one crate/package you don't actually need to list the lib as a dependency of the bin. I wasn't aware of this - my mistake!

Thanks so much @seventh-chord!
