### ISSUE TITLE
Screen freeze when executing SEI in stepping mode

### ISSUE THREAD

**Issue by daschfg** [simon-whitehead/hakka#7]
Currently setting the interrupt disabled flag disables the renderer. So with the new console depending on the renderer as well, the screen freezes as soon as you execute the `SEI` instruction in stepping mode.

A workaround for this could be to make rendering independent of the interrupt flag again, while only disabling the game logic. Any other ideas on this?
I would offer looking further into this issue if you want.

**Comment by simon-whitehead** [comment]
Nice find! I had not considered this to be honest.

You are welcome to look further in to this if you would like to 😃 

> Any other ideas on this?

I think, if the player is currently debugging and has stepped over an `SEI`, it is appropriate to not bother rendering the game. So my idea would be: Move the `renderer.clear()` and `renderer.present()` calls out of the interrupt flag check and place the `vm.render()` call outside as well.

So currently its:

    if !cpu.interrupt_disabled {
        renderer.clear();
        render_lots_of_stuff();
        vm.render();
        renderer.present();
     }

I think its fine if we did this:

    renderer.clear();
    if !cpu.interrupt_disabled {
        render_lots_of_stuff();
    }  
    vm.render();
    renderer.present();

What do you think? Is it okay that the game fails to render the scene properly if the player has stepped over an `SEI`?

**Comment by daschfg** [comment]
So that it only shows a blank screen instead of the fully rendered ship when the flag is set? I like the idea, seems like a reasonable and simpler solution.
I'm not sure as I have no experience with this, but do you know if disabling interrupts would affect the sync to display on a real machine as well?

**Comment by simon-whitehead** [comment]
> but do you know if disabling interrupts would affect the sync to display on a real machine as well?

The technique I used here was a very "quick and dirty" solution to the issues I was facing during the prototyping stage. In a typical NES game for example, the game itself will draw the assets during the VBlank stage of the PPU (when its gone idle). They generally set flags internally (in memory at some random address) to signal that during the next VBlank they can render the scene. 

I think to make the game similar to this, it would be best for the game to set a flag (instead of use `SEI`) that the Rust gameloop can check for whether it can both a) Process the game logic (the ship position) and b) Render the scene.

For this initial proof of concept I don't think the process needs to change. I think, as each new level in the game is added we will have to approach it on a case-by-case basis.

**Comment by simon-whitehead** [comment]
This is being addressed in #8
